### ISSUE TITLE
"sprites/bullets/bullets.atlas" file is missing

### ISSUE THREAD

**Issue by ascriptmaster** [Java2hu/Java2hu#2]
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: File not found: sprites\bullets\bullets.atlas (Internal)
    at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
    at com.badlogic.gdx.graphics.g2d.TextureAtlas$TextureAtlasData.<init>(TextureAtlas.java:103)
    at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:231)
    at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:226)
    at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:216)
    at java2hu.touhou.bullet.LegacyTouhouBulletMaker$2.run(LegacyTouhouBulletMaker.java:73)
    at java2hu.J2hGame.updateStageLogic(J2hGame.java:1749)
    at java2hu.J2hGame.render(J2hGame.java:2258)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:214)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```

I was attempting to run using Gradle 2.6 (the newest release).

**Comment by sylvia43** [comment]
It's a misconfiguration of your working directory. Your working directory should be set to `[PROJECT_DIR]/core/assets/`. LibGDX bases relative paths to load assets on your working directory.

We really need that readme :/

**Comment by ascriptmaster** [comment]
I tried from every folder I could think of. Also, running `find [PROJECT_DIR] -name bullets.atlas` didn't return any files. Do I need to run from Eclipse instead, or something?

**Comment by sylvia43** [comment]
Oh huh that file isn't in the repository... @Java2hu?

I've been pretty busy this week, but I'll have time tonight. I'd be down to jump on a call and figure things out. UTC-4.

**Comment by ascriptmaster** [comment]
No response?

**Comment by ascriptmaster** [comment]
@anubiann00b, if @Java2hu doesn't respond, is it possible for you to add `bullets.atlas` in their place?

**Comment by sylvia43** [comment]
@ascriptmaster  I don't have a copy of that file unfortunately :/

My email is on my profile, let's get on skype or hangouts sometime this weekend (or tonight) and figure this out. I don't want to lose someone so interested in the project, and I personally haven't done much of anything towards this in a while, I've been incredibly busy this summer.

**Comment by sylvia43** [comment]
I've contacted @Java2hu about it. Hopefully he responds...

**Comment by Java2hu** [comment]
My bad, never noticed it was missing! I'll add it to the repo asap.
